version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - blue
      - green
    networks:
      - app-network
  blue:
    build: .
    ports:
      - "3000:3000"  # 추가: 호스트의 3000번 포트와 컨테이너의 3000번 포트 매핑
    networks:
      - app-network
    environment:
      - PORT=3000
  green:
    build: .
    ports:
      - "3002:3000"  # 추가: 호스트의 3002번 포트와 컨테이너의 3000번 포트 매핑
    networks:
      - app-network
    environment:
      - PORT=3000
networks:
  app-network:
    driver: bridge
