name: numbers_crm CI/CD
on:
 push:
   branches: [ main, develop ]
 pull_request:
   branches: [ main, develop ]
jobs:
 test:
   runs-on: ubuntu-latest
   services:
     postgres:
       image: postgres:latest
       env:
         POSTGRES_DB: ${{ secrets.DB_NAME }}
         POSTGRES_USER: ${{ secrets.DB_USER }}
         POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
       ports:
         - 5432:5432
       options: >-
         --health-cmd pg_isready
         --health-interval 10s
         --health-timeout 5s
         --health-retries 5
   steps:
     - uses: actions/checkout@v3
     - name: Setup Node.js
       uses: actions/setup-node@v3
       with:
         node-version: '18'
         cache: 'yarn'
     - name: Check environment
       run: |
         node -v
         yarn -v
         pwd
         ls -la
     - name: Install dependencies
       run: |
         yarn install
         yarn add -D eslint-config-airbnb-base eslint-config-airbnb-typescript @typescript-eslint/eslint-plugin @typescript-eslint/parser
     - name: Run tests
       run: yarn test --passWithNoTests
       env:
         DATABASE_URL: postgresql://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@adhd.cvdkz8ngl0rg.ap-northeast-2.rds.amazonaws.com:5432/${{ secrets.DB_NAME }}
     - name: Build
       run: yarn build
 
 deploy-develop:
   needs: test
   if: github.ref == 'refs/heads/develop'
   runs-on: ubuntu-latest
   steps:
     - name: Deploy to Dev Server
       uses: appleboy/ssh-action@master
       with:
         host: ${{ secrets.DEV_HOST }}
         username: ${{ secrets.SSH_USERNAME }}
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         script: |
           # Node.js, npm, Yarn, PM2 설치 (sudo 사용)
           sudo apt-get update
           sudo apt-get install -y nodejs npm
           sudo npm install -g n
           sudo n stable
           sudo npm install -g yarn pm2

           # 프로젝트 디렉토리 준비
           mkdir -p ~/numbers_crm
           cd ~/numbers_crm

           # Git 저장소 업데이트
           if [ ! -d .git ]; then
             git init
             git remote add origin https://github.com/adh-number-001/numbers_crm_server.git
           fi
           git fetch
           git checkout develop
           git pull origin develop

           # 의존성 설치 및 빌드
           yarn install
           yarn build

           # PM2로 애플리케이션 시작 (기존 프로세스 삭제 후 재시작)
           pm2 delete numbers-crm-api-dev || true
           pm2 start dist/main.js --name numbers-crm-api-dev
 
 deploy-production:
   needs: test
   if: github.ref == 'refs/heads/main'
   runs-on: ubuntu-latest
   steps:
     - name: Deploy to Production
       uses: appleboy/ssh-action@master
       with:
         host: ${{ secrets.PROD_HOST }}
         username: ${{ secrets.SSH_USERNAME }}
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         script: |
           # Node.js, npm, Yarn, PM2 설치 (sudo 사용)
           sudo apt-get update
           sudo apt-get install -y nodejs npm
           sudo npm install -g n
           sudo n stable
           sudo npm install -g yarn pm2

           # 프로젝트 디렉토리 준비
           mkdir -p ~/numbers_crm
           cd ~/numbers_crm

           # Git 저장소 업데이트
           if [ ! -d .git ]; then
             git init
             git remote add origin https://github.com/adh-number-001/numbers_crm_server.git
           fi
           git fetch
           git checkout main
           git pull origin main

           # 의존성 설치 및 빌드
           yarn install
           yarn build

           # PM2로 애플리케이션 시작 (기존 프로세스 삭제 후 재시작)
           pm2 delete numbers-crm-api-prod || true
           pm2 start dist/main.js --name numbers-crm-api-prod
