name: numbers_crm CI/CD
on:
  push:
    branches: [main] # ✅ main 푸시 시 배포 실행

jobs:
  debug-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Check SSH Connectivity
        run: |
          nc -zv ${{ secrets.PROD_HOST }} 22
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Connect to EC2 and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 프로젝트 디렉토리 이동
            cd ~/numbers_crm

            # 환경 변수 설정
            export NODE_ENV=prod
            echo "NODE_ENV set to $NODE_ENV"

            # 최신 코드 가져오기
            git fetch --all
            git reset --hard origin/main
            git pull origin main

            # package.json 또는 yarn.lock 변경 시에만 yarn install 실행
            if git diff --quiet HEAD~1 -- package.json yarn.lock; then
              echo "No dependency changes, skipping yarn install"
            else
              yarn install --frozen-lockfile
            fi

            # Prisma 마이그레이션 적용 (DB 스키마 최신화)
            yarn prisma migrate deploy
            yarn prisma generate  # Prisma Client 최신화

            # 소스 코드 변경 여부 확인 후 빌드 실행
            if git diff --quiet HEAD~1 -- src/; then
              echo "No source code changes, skipping build"
            else
              yarn build
            fi

            # PM2로 서비스 재시작
            if pm2 list | grep -q "numbers-crm-api-prod"; then
              pm2 reload numbers-crm-api-prod
            else
              pm2 start dist/src/main.js --name numbers-crm-api-prod
            fi

            # PM2 상태 확인
            pm2 list
